version: "3.8"
services:
  streamlit:
    build:
      context: .
    container_name: streamlit-app
    ports:
      - "8501:8501"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
